### ISSUE TITLE
update jwt library

### ISSUE THREAD

**Issue by jgrangethales** [ThalesGroup/sshizzle#13]
dependabot alert [ Authorization bypass in github.com/dgrijalva/jwt-go shows ](https://github.com/ThalesGroup/sshizzle/security/dependabot/1) is high severity - this library has been migrated to new repo, and no security fixes available  on this repo.

New repo is: https://github.com/golang-jwt/jwt - there are v3.2.1 and v3.2.2 versions which should fix the issue.  There are also v4.x versions, but will require work to determine comatibility

**Comment by Sebastienlejeune** [comment]
Yes if possible try to move to the 3.2.2 version of golang-jwt

Thanks in advance

Envoyé depuis Workspace ONE Boxer

Le 2 nov. 2022 09:53, John Grange ***@***.***> a écrit :

dependabot alert Authorization bypass in github.com/dgrijalva/jwt-go shows <https://github.com/ThalesGroup/sshizzle/security/dependabot/1> is high severity - this library has been migrated to new repo, and no security fixes available on this repo.

New repo is: https://github.com/golang-jwt/jwt - there are v3.2.1 and v3.2.2 versions which should fix the issue. There are also v4.x versions, but will require work to determine comatibility
